name: SwiftLint

on:
  pull_request:
    branches: [main]  # Change to your default branch

jobs:
  lint:
    name: Run SwiftLint
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: |
          swiftlint lint --strict
          if [ $? -ne 0 ]; then
            echo "SwiftLint failed, blocking merge."
            exit 1
          fi